version: '3.1'

services:
  backend:
    build: ./backend
    environment:
      POSTGRES_PASSWORD: secret
      SECRET_KEY: secret
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
