version: '3.8'

services:
  test:
    build: ./backend
    command: ['pytest']
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  worker:
    build: ./worker
    env_file:
      - ./worker/.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 8081:15672
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: secret

