import os

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv("DEBUG") or False

SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")
